### ISSUE TITLE
No support for linux

### ISSUE THREAD

**Issue by gold-is-eepy-now** [PlayNowKnux/VibRibbonMinusRelease#4]
I Use ubuntu and would like to play VRM Without the hassle of using wine.

**Comment by Fussmatte** [comment]
For what it's worth, the game seems to run OK using Proton, if you add it to Steam as a non-Steam game. But a Linux port would be nice.

**Comment by PlayNowKnux** [comment]
If you install Python >=3.10 and the game's dependencies, you can run it natively on Linux

**Comment by PlayNowKnux** [comment]
To make this more clear, do not download the Vib-Ribbon Minus Windows release. Instead, download the source code, Python >= 3.10, pygame and mutagen (via pip), and run main.py
